Adding some stuff.

diff --git a/scripts/sneks_publish-sam-stack b/scripts/sneks_publish-sam-stack
--- a/scripts/sneks_publish-sam-stack
+++ b/scripts/sneks_publish-sam-stack
@@ -16,14 +16,14 @@ if [ -z "$CONFFILE" ] ; then
 fi
 
 if [ -f "$CONFFILE" ] ; then
-    eval `get_sam_args -f $CONFFILE`
+    eval `sneks get-sam-args -f $CONFFILE`
 else
-    eval `get_sam_args`
+    eval `sneks get-sam-args`
 fi
 
-setup_build_dir || abort "'setup_build_dir' failed"
+sneks setup-build-dir || abort "'setup_build_dir' failed"
 echo "$BUILD_PARAMS" > build/extra_params.json
-bundle_lambda || abort "'bundle_lambda' failed"
+sneks bundle-lambda || abort "'bundle_lambda' failed"
 
 aws --region $AWS_REGION --profile $AWS_PROFILE \
     cloudformation deploy \
